### ISSUE TITLE
Licesing

### ISSUE THREAD

**Issue by gautammaloo** [joyent/mi-centos-7#2]
Hi,
I have forked this repo to build custom ISO with centos+xen+networking https://github.com/gautammaloo/centos-xen

I want to use it further for my gsoc-2015 project (https://www.google-melange.com/gsoc/project/details/google/gsoc2015/gautam_malu/5717271485874176).  But I need to make sure that this repo is released under MIT or GPL license. Can you add a license to it?

**Comment by chorrell** [comment]
We typically release under Mozilla Public License Version 2.0. Is that an issue?

**Comment by gautammaloo** [comment]
@chorrell Yeah that should work :-)

**Comment by chorrell** [comment]
OK cool, I'll add the LICENSE now :)
