### ISSUE TITLE
Already have the ISO

### ISSUE THREAD

**Issue by bertalanimre** [joyent/mi-centos-7#3]
Hello,

How can I tell create_iso that I already have the ISO file in a custom location? Or I have to create that /data folder with the rest and put it there?

B.R.:
Bert

**Comment by chorrell** [comment]
You would probably need to customize the `fetch_iso` function

**Comment by bertalanimre** [comment]
Already did and also thinking about a few other adjustments. Gonna push them to my fork and then you can check them out. If you'll like you can build it in your app.

**Comment by chorrell** [comment]
Thanks! At some point though I'm probably going to setup a new build repo for CentOS images that's a lot flexible, similar to what I did here: 

https://github.com/joyent/fedora-kvm-image-builder
